# Generated by Django 4.2.16 on 2026-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="advance_payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "M-Pesa / Mobile Money"),
                    ("cheque", "Cheque"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                help_text="How was the advance payment received?",
                max_length=20,
            ),
        ),
    ]
