# Generated by Django 4.2.16 on 2026-04-01 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_materialorder_payment_source"),
        ("projects", "0002_projectevent"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creditor_name",
                    models.CharField(
                        help_text="Person or company we owe", max_length=200
                    ),
                ),
                ("creditor_phone", models.CharField(blank=True, max_length=30)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("supplier_credit", "Supplier Credit (Materials)"),
                            ("personal_loan", "Personal Loan"),
                            ("company_loan", "Company / Business Loan"),
                            ("other", "Other"),
                        ],
                        default="supplier_credit",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount owed", max_digits=14
                    ),
                ),
                ("date_incurred", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(help_text="What is this debt for?")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "Outstanding"),
                            ("partial", "Partially Paid"),
                            ("settled", "Fully Settled"),
                        ],
                        default="outstanding",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Order that created this debt (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debts",
                        to="orders.materialorder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Debts",
                "ordering": ["-date_incurred"],
            },
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_source",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("mpesa", "M-Pesa / Mobile Money"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        help_text="Where did the repayment money come from?",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.debt",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
