# Generated by Django 4.2.16 on 2026-04-01 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficeServiceRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_per_window",
                    models.DecimalField(
                        decimal_places=2, help_text="TZS per window", max_digits=10
                    ),
                ),
                (
                    "rate_per_door",
                    models.DecimalField(
                        decimal_places=2, help_text="TZS per door", max_digits=10
                    ),
                ),
                ("effective_from", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="OfficeServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_phone", models.CharField(blank=True, max_length=30)),
                ("client_address", models.TextField(blank=True)),
                (
                    "work_description",
                    models.TextField(
                        blank=True, help_text="Describe the windows/doors work"
                    ),
                ),
                ("num_windows", models.PositiveIntegerField(default=0)),
                ("num_doors", models.PositiveIntegerField(default=0)),
                (
                    "rate_per_window",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rate_per_door",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_recorded", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("partial", "Partially Paid"),
                            ("paid", "Fully Paid"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.CreateModel(
            name="OfficeServicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("cheque", "Cheque"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="office.officeservicerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="OfficeIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("project_profit", "Project Profit"),
                            ("office_service", "Office Service Charge"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "office_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="office.officeservicerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
