# Generated by Django 4.2.16 on 2026-04-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeincome",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("mpesa", "M-Pesa / Mobile Money"),
                    ("cheque", "Cheque"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                max_length=15,
            ),
        ),
    ]
