# Generated by Django 4.2.16 on 2026-04-01 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("actual_delivery", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ordered", "Ordered"),
                            ("partially_received", "Partially Received"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("m2", "m² (Square Meters)"),
                            ("pcs", "Pcs (Pieces)"),
                            ("kg", "Kg (Kilograms)"),
                            ("m", "m (Meters)"),
                            ("set", "Set"),
                            ("box", "Box"),
                        ],
                        default="m2",
                        max_length=10,
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.materialorder",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
    ]
