# Generated by Django 4.2.16 on 2026-04-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorder",
            name="payment_source",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("mpesa", "M-Pesa / Mobile Money"),
                    ("cheque", "Cheque"),
                    ("unspecified", "Not specified"),
                ],
                default="unspecified",
                help_text="Where did the money come from to pay for this order?",
                max_length=15,
            ),
        ),
    ]
