# Generated by Django 4.2.16 on 2026-03-31 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price_per_sqm", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_no", models.CharField(blank=True, max_length=30, unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("client_phone", models.CharField(blank=True, max_length=30)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_address", models.TextField(blank=True)),
                ("project_name", models.CharField(blank=True, max_length=300)),
                (
                    "installation_days",
                    models.PositiveIntegerField(default=7, help_text="Working days"),
                ),
                ("notes", models.TextField(blank=True)),
                ("quote_date", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Client"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("discount_name", models.CharField(blank=True, max_length=100)),
                ("discount_duration", models.CharField(blank=True, max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("fixed", "Fixed Amount (TZS)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("vat_enabled", models.BooleanField(default=False)),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                ("service_levy_enabled", models.BooleanField(default=False)),
                (
                    "service_levy_rate",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
                ),
                ("skills_levy_enabled", models.BooleanField(default=False)),
                (
                    "skills_levy_rate",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
                ),
                ("withholding_enabled", models.BooleanField(default=False)),
                (
                    "withholding_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                ("custom1_name", models.CharField(blank=True, max_length=100)),
                (
                    "custom1_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("custom1_enabled", models.BooleanField(default=False)),
                ("custom2_name", models.CharField(blank=True, max_length=100)),
                (
                    "custom2_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("custom2_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("price_per_sqm", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_materials",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        help_text="e.g. Casement Window, Sliding Door", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Width in cm", max_digits=8
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, help_text="Height in cm", max_digits=8
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
